import pandas as pd

df = pd.read_csv('backend/data/spotify_tracks.csv')

additional_tracks = [
    {
        'track_id': '602h3f2n4k5j6l1a',
        'artists': 'Hans Zimmer',
        'album_name': 'Inception (Music from the Motion Picture)',
        'track_name': 'Time',
        'popularity': 89,
        'duration_ms': 275000,
        'explicit': False,
        'danceability': 0.18,
        'energy': 0.45,
        'key': 7,
        'loudness': -13.5,
        'mode': 1,
        'speechiness': 0.03,
        'acousticness': 0.88,
        'instrumentalness': 0.96,
        'liveness': 0.09,
        'valence': 0.08,
        'tempo': 68.0,
        'time_signature': 4,
        'track_genre': 'soundtrack',
        'album_art': 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80'
    },
    {
        'track_id': '7891234567abcdef',
        'artists': 'Hans Zimmer',
        'album_name': 'The Dark Knight (Original Motion Picture Soundtrack)',
        'track_name': 'Why So Serious?',
        'popularity': 82,
        'duration_ms': 554000,
        'explicit': False,
        'danceability': 0.22,
        'energy': 0.81,
        'key': 2,
        'loudness': -9.2,
        'mode': 0,
        'speechiness': 0.05,
        'acousticness': 0.45,
        'instrumentalness': 0.91,
        'liveness': 0.18,
        'valence': 0.12,
        'tempo': 140.0,
        'time_signature': 4,
        'track_genre': 'soundtrack',
        'album_art': 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80'
    },
    {
        'track_id': '1234567890abcdef',
        'artists': 'Hans Zimmer',
        'album_name': 'Dune (Original Motion Picture Soundtrack)',
        'track_name': 'Paul\'s Dream',
        'popularity': 86,
        'duration_ms': 423000,
        'explicit': False,
        'danceability': 0.15,
        'energy': 0.76,
        'key': 5,
        'loudness': -8.1,
        'mode': 0,
        'speechiness': 0.04,
        'acousticness': 0.52,
        'instrumentalness': 0.93,
        'liveness': 0.14,
        'valence': 0.11,
        'tempo': 115.0,
        'time_signature': 4,
        'track_genre': 'soundtrack',
        'album_art': 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80'
    },
    {
        'track_id': 'fedcba0987654321',
        'artists': 'Ludwig Göransson',
        'album_name': 'Tenet (Original Motion Picture Soundtrack)',
        'track_name': 'POSTERITY',
        'popularity': 78,
        'duration_ms': 462000,
        'explicit': False,
        'danceability': 0.42,
        'energy': 0.88,
        'key': 1,
        'loudness': -6.4,
        'mode': 0,
        'speechiness': 0.045,
        'acousticness': 0.08,
        'instrumentalness': 0.89,
        'liveness': 0.15,
        'valence': 0.20,
        'tempo': 135.0,
        'time_signature': 4,
        'track_genre': 'soundtrack',
        'album_art': 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80'
    },
    {
        'track_id': '3456789012abcdef',
        'artists': 'The Weeknd',
        'album_name': 'After Hours',
        'track_name': 'Blinding Lights',
        'popularity': 96,
        'duration_ms': 200000,
        'explicit': False,
        'danceability': 0.51,
        'energy': 0.73,
        'key': 1,
        'loudness': -5.9,
        'mode': 1,
        'speechiness': 0.06,
        'acousticness': 0.001,
        'instrumentalness': 0.0001,
        'liveness': 0.09,
        'valence': 0.33,
        'tempo': 171.0,
        'time_signature': 4,
        'track_genre': 'synthpop',
        'album_art': 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80'
    },
    {
        'track_id': '9876543210fedcba',
        'artists': 'Daft Punk',
        'album_name': 'Random Access Memories',
        'track_name': 'Get Lucky (feat. Pharrell Williams)',
        'popularity': 90,
        'duration_ms': 248000,
        'explicit': False,
        'danceability': 0.79,
        'energy': 0.81,
        'key': 11,
        'loudness': -5.7,
        'mode': 0,
        'speechiness': 0.04,
        'acousticness': 0.04,
        'instrumentalness': 0.00005,
        'liveness': 0.10,
        'valence': 0.86,
        'tempo': 116.0,
        'time_signature': 4,
        'track_genre': 'disco',
        'album_art': 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80'
    },
    {
        'track_id': 'abcdef1234567890',
        'artists': 'Kavinsky',
        'album_name': 'OutRun',
        'track_name': 'Pacific Coast Highway',
        'popularity': 76,
        'duration_ms': 382000,
        'explicit': False,
        'danceability': 0.52,
        'energy': 0.79,
        'key': 4,
        'loudness': -7.1,
        'mode': 0,
        'speechiness': 0.038,
        'acousticness': 0.02,
        'instrumentalness': 0.85,
        'liveness': 0.11,
        'valence': 0.29,
        'tempo': 108.0,
        'time_signature': 4,
        'track_genre': 'synthwave',
        'album_art': 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&auto=format&fit=crop&q=80'
    },
    {
        'track_id': 'bcdfgh1234567890',
        'artists': 'Tycho',
        'album_name': 'Dive',
        'track_name': 'A Walk',
        'popularity': 80,
        'duration_ms': 316000,
        'explicit': False,
        'danceability': 0.62,
        'energy': 0.55,
        'key': 9,
        'loudness': -9.8,
        'mode': 1,
        'speechiness': 0.028,
        'acousticness': 0.28,
        'instrumentalness': 0.92,
        'liveness': 0.08,
        'valence': 0.48,
        'tempo': 100.0,
        'time_signature': 4,
        'track_genre': 'ambient',
        'album_art': 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80'
    },
    {
        'track_id': 'zxcvbn1234567890',
        'artists': 'M83',
        'album_name': 'Oblivion (Original Motion Picture Soundtrack)',
        'track_name': 'StarWaves',
        'popularity': 74,
        'duration_ms': 221000,
        'explicit': False,
        'danceability': 0.25,
        'energy': 0.72,
        'key': 6,
        'loudness': -8.4,
        'mode': 1,
        'speechiness': 0.032,
        'acousticness': 0.65,
        'instrumentalness': 0.94,
        'liveness': 0.09,
        'valence': 0.16,
        'tempo': 120.0,
        'time_signature': 4,
        'track_genre': 'soundtrack',
        'album_art': 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80'
    },
    {
        'track_id': 'qwertz1234567890',
        'artists': 'Radiohead',
        'album_name': 'OK Computer',
        'track_name': 'Karma Police',
        'popularity': 85,
        'duration_ms': 264000,
        'explicit': False,
        'danceability': 0.36,
        'energy': 0.51,
        'key': 7,
        'loudness': -9.3,
        'mode': 0,
        'speechiness': 0.031,
        'acousticness': 0.39,
        'instrumentalness': 0.001,
        'liveness': 0.10,
        'valence': 0.22,
        'tempo': 75.0,
        'time_signature': 4,
        'track_genre': 'alternative',
        'album_art': 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80'
    }
]

df_extra = pd.DataFrame(additional_tracks)
df_all = pd.concat([df, df_extra], ignore_index=True)
df_all.to_csv('backend/data/spotify_tracks.csv', index=False)
print(f"SUCCESS: Expanded spotify_tracks.csv to {len(df_all)} tracks.")
