import { Movie, Song } from '@/types';

export const MOCK_MOVIES: Movie[] = [
  {
    id: 'm-forrest-gump',
    title: 'Forrest Gump',
    overview: 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined possible. Yet, despite all he has achieved, his one true love eludes him.',
    poster_path: 'https://image.tmdb.org/t/p/w780/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/qdIMHd4sEfJSckfVJfKQvisL02a.jpg',
    release_date: '1994-07-06',
    vote_average: 8.5,
    genres: ['Drama', 'Romance', 'Comedy'],
    language: 'English',
    runtime: 142,
    match_score: 99,
    agent_rationale: 'Academy Award Winner for Best Picture. Pure cinematic storytelling with Tom Hanks unforgettable performance.'
  },
  {
    id: 'm-mirzapur',
    title: 'Mirzapur',
    overview: 'A shocking incident at a wedding procession ignites a series of events entangling two families in the lawless city of Mirzapur.',
    poster_path: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=700&auto=format&fit=crop&q=80',
    backdrop_path: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=1200&auto=format&fit=crop&q=80',
    release_date: '2024-07-05',
    vote_average: 8.5,
    genres: ['Action', 'Thriller', 'Drama'],
    language: 'Hindi',
    runtime: 55,
    match_score: 97,
    agent_rationale: 'High-stakes gritty Indian crime drama with raw character arcs.'
  },
  {
    id: 'm-shawshank',
    title: 'The Shawshank Redemption',
    overview: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    poster_path: 'https://image.tmdb.org/t/p/w780/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
    release_date: '1994-09-23',
    vote_average: 9.3,
    genres: ['Drama', 'Classic'],
    language: 'English',
    runtime: 142,
    match_score: 98,
    agent_rationale: 'All-time IMDb #1 masterpiece of resilience, hope, and friendship.'
  },
  {
    id: 'm-american-psycho',
    title: 'American Psycho',
    overview: 'A wealthy New York City investment banking executive hides his alternate psychopathic ego from his co-workers and friends.',
    poster_path: 'https://image.tmdb.org/t/p/w780/9uGHEgsiUXjCNq8wdq4r49YL8A1.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/qdIMHd4sEfJSckfVJfKQvisL02a.jpg',
    release_date: '2000-04-14',
    vote_average: 7.6,
    genres: ['Thriller', 'Comedy', 'Drama'],
    language: 'English',
    runtime: 102,
    match_score: 94,
    agent_rationale: 'Sharp dark satire and psychological horror with iconic performances.'
  },
  {
    id: 'm-dark-knight',
    title: 'The Dark Knight',
    overview: 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets.',
    poster_path: 'https://image.tmdb.org/t/p/w780/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
    release_date: '2008-07-18',
    vote_average: 8.5,
    genres: ['Action', 'Crime', 'Drama', 'Thriller'],
    language: 'English',
    runtime: 152,
    match_score: 99,
    agent_rationale: 'Christopher Nolan masterpiece featuring Heath Ledger legendary Oscar-winning performance.'
  },
  {
    id: 'm-parasite',
    title: 'Parasite (기생충)',
    overview: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    poster_path: 'https://image.tmdb.org/t/p/w780/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg',
    release_date: '2019-10-11',
    vote_average: 8.5,
    genres: ['Thriller', 'Drama', 'Comedy'],
    language: 'Korean',
    runtime: 132,
    match_score: 97,
    agent_rationale: 'Bong Joon-ho Oscar-winning masterpiece blending razor-sharp satire and suspense.'
  },
  {
    id: 'm-spiritedaway',
    title: 'Spirited Away (千と千尋の神隠し)',
    overview: 'During her family’s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
    poster_path: 'https://image.tmdb.org/t/p/w780/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/mSDsSDwaP3E7dviUU2ioXPsq9d2.jpg',
    release_date: '2001-07-20',
    vote_average: 8.6,
    genres: ['Anime', 'Sci-Fi', 'Adventure'],
    language: 'Japanese',
    runtime: 125,
    match_score: 98,
    agent_rationale: 'Hayao Miyazaki and Studio Ghibli crowning achievement in fantasy animation.'
  },
  {
    id: 'm-inception',
    title: 'Inception',
    overview: 'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: inception.',
    poster_path: 'https://image.tmdb.org/t/p/w780/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
    release_date: '2010-07-16',
    vote_average: 8.4,
    genres: ['Action', 'Sci-Fi', 'Adventure'],
    language: 'English',
    runtime: 148,
    match_score: 98,
    agent_rationale: 'Mind-bending dream heist cinema with Hans Zimmer iconic score.'
  },
  {
    id: 'm-interstellar',
    title: 'Interstellar',
    overview: 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
    poster_path: 'https://image.tmdb.org/t/p/w780/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/pbrkL804c8yAv3zBZR4QPEafpAR.jpg',
    release_date: '2014-11-07',
    vote_average: 8.7,
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    language: 'English',
    runtime: 169,
    match_score: 99,
    agent_rationale: 'Epic space voyage exploring love, time dilation, and human survival.'
  },
  {
    id: 'm-gladiator',
    title: 'Gladiator',
    overview: 'In the year 180, the death of Emperor Marcus Aurelius throws the Roman Empire into turmoil. When Maximus Decimus Meridius is betrayed and his family murdered, he is forced into slavery as a gladiator to avenge their deaths.',
    poster_path: 'https://image.tmdb.org/t/p/w780/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/3ZVEtQxVPpEp5LNpAULDcxadTU3.jpg',
    release_date: '2000-05-05',
    vote_average: 8.5,
    genres: ['Action', 'Drama', 'Adventure'],
    language: 'English',
    runtime: 155,
    match_score: 97,
    agent_rationale: 'Epic historical drama directed by Ridley Scott with timeless score by Hans Zimmer.'
  },
  {
    id: 'm-batman',
    title: 'The Batman',
    overview: 'In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.',
    poster_path: 'https://image.tmdb.org/t/p/w780/74xTEgt7R36Fpooo50r9T25onhq.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/tRS6jvPM9qPrrnx2KRx2ew96Yot.jpg',
    release_date: '2022-03-04',
    vote_average: 8.2,
    genres: ['Action', 'Thriller', 'Drama'],
    language: 'English',
    runtime: 176,
    match_score: 93,
    agent_rationale: 'Dark atmospheric crime thriller with intense pacing and Michael Giacchino score.'
  },
  {
    id: 'm-deadpool',
    title: 'Deadpool',
    overview: 'A wisecracking mercenary gets experimented on and becomes immortal but ugly, and sets out to track down the man who ruined his looks.',
    poster_path: 'https://image.tmdb.org/t/p/w780/zq8Cl3PNIDGU3iWNRoc5nEZ6pCe.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/en971MEXui9diirXlogOrPKmsEn.jpg',
    release_date: '2016-02-12',
    vote_average: 7.6,
    genres: ['Action', 'Adventure', 'Comedy'],
    language: 'English',
    runtime: 108,
    match_score: 95,
    agent_rationale: 'Hilarious, boundary-pushing meta-superhero comedy with relentless action.'
  },
  {
    id: 'm-avengers',
    title: 'The Avengers',
    overview: 'Earth\'s mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.',
    poster_path: 'https://image.tmdb.org/t/p/w780/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg',
    release_date: '2012-05-04',
    vote_average: 7.7,
    genres: ['Action', 'Sci-Fi', 'Adventure'],
    language: 'English',
    runtime: 143,
    match_score: 96,
    agent_rationale: 'Groundbreaking superhero ensemble film that reshaped blockbuster cinema.'
  },
  {
    id: 'm-spiderverse',
    title: 'Spider-Man: Across the Spider-Verse',
    overview: 'Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence. When the heroes clash on how to handle a threat, Miles must redefine what it means to be a hero.',
    poster_path: 'https://image.tmdb.org/t/p/w780/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
    release_date: '2023-06-02',
    vote_average: 8.8,
    genres: ['Animation', 'Action', 'Sci-Fi', 'Adventure'],
    language: 'English',
    runtime: 140,
    match_score: 99,
    agent_rationale: 'Visually miraculous animation triumph blending multiple art styles into pure comic book kinetic energy.'
  },
  {
    id: 'm-oppenheimer',
    title: 'Oppenheimer',
    overview: 'The pulse-pounding story of J. Robert Oppenheimer and the Manhattan Project — racing against the Nazis to build the atomic bomb and confronting the catastrophic reality of what came next.',
    poster_path: 'https://image.tmdb.org/t/p/w780/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
    release_date: '2023-07-21',
    vote_average: 8.8,
    genres: ['Drama', 'History', 'Thriller', 'Biography'],
    language: 'English',
    runtime: 180,
    match_score: 98,
    agent_rationale: '7 Academy Awards winner including Best Picture and Best Director for Christopher Nolan.'
  },
  {
    id: 'm-dune2',
    title: 'Dune: Part Two',
    overview: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
    poster_path: 'https://image.tmdb.org/t/p/w780/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5200SV.jpg',
    release_date: '2024-03-01',
    vote_average: 8.7,
    genres: ['Sci-Fi', 'Adventure', 'Action', 'Drama'],
    language: 'English',
    runtime: 166,
    match_score: 98,
    agent_rationale: 'Monumental sci-fi epic by Denis Villeneuve with staggering scale and Hans Zimmer percussion score.'
  },
  {
    id: 'm-bladerunner2049',
    title: 'Blade Runner 2049',
    overview: 'Young Blade Runner K\'s discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who\'s been missing for thirty years.',
    poster_path: 'https://image.tmdb.org/t/p/w780/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/sAtoMqDVhNDQBc3QJL3RF6hl7q6.jpg',
    release_date: '2017-10-06',
    vote_average: 8.0,
    genres: ['Sci-Fi', 'Mystery', 'Drama', 'Thriller'],
    language: 'English',
    runtime: 164,
    match_score: 96,
    agent_rationale: 'Breathtaking neo-noir cyberpunk visual masterpiece with Roger Deakins Oscar-winning cinematography.'
  },
  {
    id: 'm-madmax',
    title: 'Mad Max: Fury Road',
    overview: 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.',
    poster_path: 'https://image.tmdb.org/t/p/w780/hA2ple9q4qnwxp3hKVNhroipsir.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/nlCHUW2Y9XWbuEUQauCBgnY8ymF.jpg',
    release_date: '2015-05-15',
    vote_average: 8.1,
    genres: ['Action', 'Sci-Fi', 'Adventure'],
    language: 'English',
    runtime: 120,
    match_score: 97,
    agent_rationale: 'High-octane practical stunt filmmaking masterclass from visionary George Miller.'
  },
  {
    id: 'm-johnwick4',
    title: 'John Wick: Chapter 4',
    overview: 'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table.',
    poster_path: 'https://image.tmdb.org/t/p/w780/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/7I6VUdPj6tQECNHdviJkUHD2389.jpg',
    release_date: '2023-03-24',
    vote_average: 7.8,
    genres: ['Action', 'Crime', 'Thriller'],
    language: 'English',
    runtime: 169,
    match_score: 95,
    agent_rationale: 'Peak martial-arts neo-noir action cinema featuring Donnie Yen and Keanu Reeves.'
  },
  {
    id: 'm-se7en',
    title: 'Se7en',
    overview: 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.',
    poster_path: 'https://image.tmdb.org/t/p/w780/6yoghtyTpznpBik8EngEmJskVUO.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/ba4CpLnvvLP4AauLa92qKq47FhS.jpg',
    release_date: '1995-09-22',
    vote_average: 8.6,
    genres: ['Crime', 'Mystery', 'Thriller', 'Drama'],
    language: 'English',
    runtime: 127,
    match_score: 97,
    agent_rationale: 'David Fincher bleak psychological thriller masterpiece with shocking climax.'
  },
  {
    id: 'm-fightclub',
    title: 'Fight Club',
    overview: 'An insomniac office worker looking for a way to change his life crosses paths with a devil-may-care soap maker and they form an underground fight club.',
    poster_path: 'https://image.tmdb.org/t/p/w780/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/hZkgoQYus5vegHoetLkCJzb17zJ.jpg',
    release_date: '1999-10-15',
    vote_average: 8.4,
    genres: ['Drama', 'Thriller'],
    language: 'English',
    runtime: 139,
    match_score: 96,
    agent_rationale: 'Cult cinema defining generational rebellion and identity.'
  },
  {
    id: 'm-pulpfiction',
    title: 'Pulp Fiction',
    overview: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    poster_path: 'https://image.tmdb.org/t/p/w780/d5iIlFnGhFvlW147Ha50slsu496.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
    release_date: '1994-10-14',
    vote_average: 8.9,
    genres: ['Crime', 'Drama', 'Comedy'],
    language: 'English',
    runtime: 154,
    match_score: 98,
    agent_rationale: 'Quentin Tarantino Palme d\'Or winning pop-culture milestone.'
  },
  {
    id: 'm-aquietplace',
    title: 'A Quiet Place',
    overview: 'A family is forced to live in silence while hiding from creatures that hunt by sound.',
    poster_path: 'https://image.tmdb.org/t/p/w780/nAU74GmpUk7t5iklEp3bufwDq4n.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/roYyPiQDytnk0mmHIKEQ395OIbT.jpg',
    release_date: '2018-04-06',
    vote_average: 7.4,
    genres: ['Horror', 'Sci-Fi', 'Thriller'],
    language: 'English',
    runtime: 90,
    match_score: 93,
    agent_rationale: 'Masterclass in atmospheric tension, acoustic design, and parental love.'
  },
  {
    id: 'm-hereditary',
    title: 'Hereditary',
    overview: 'A grieving family is haunted by tragic and disturbing occurrences after the death of their secretive grandmother.',
    poster_path: 'https://image.tmdb.org/t/p/w780/h99p4L0wEQa5w1VbQ1b8h4AflQ6.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/4fZw1yN76fRk7NlK5j8oF9wV3bH.jpg',
    release_date: '2018-06-08',
    vote_average: 7.3,
    genres: ['Horror', 'Mystery', 'Drama'],
    language: 'English',
    runtime: 127,
    match_score: 92,
    agent_rationale: 'Ari Aster chilling psychological dread and supernatural horror.'
  },
  {
    id: 'm-conjuring',
    title: 'The Conjuring',
    overview: 'Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.',
    poster_path: 'https://image.tmdb.org/t/p/w780/wVYREutTvI2tmxr6ujrHT704wGF.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/kHqT7Z1cO462n67H7uWfI3R4f14.jpg',
    release_date: '2013-07-19',
    vote_average: 7.5,
    genres: ['Horror', 'Mystery', 'Thriller'],
    language: 'English',
    runtime: 112,
    match_score: 94,
    agent_rationale: 'James Wan modern horror classic with exquisite suspense craftsmanship.'
  },
  {
    id: 'm-getout',
    title: 'Get Out',
    overview: 'A young African-American visits his white girlfriend\'s parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.',
    poster_path: 'https://image.tmdb.org/t/p/w780/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/m9hFfB9WvO9N6Lz7P7lH9oQ2Z8o.jpg',
    release_date: '2017-02-24',
    vote_average: 7.7,
    genres: ['Horror', 'Mystery', 'Thriller'],
    language: 'English',
    runtime: 104,
    match_score: 95,
    agent_rationale: 'Jordan Peele Oscar-winning psychological horror and social satire.'
  },
  {
    id: 'm-yourname',
    title: 'Your Name (君の名は。)',
    overview: 'Two teenagers share a profound, magical connection upon discovering they are swapping bodies. Things become even more complicated when the boy and girl decide to meet in person.',
    poster_path: 'https://image.tmdb.org/t/p/w780/q719jXXEzOoYaps6qFsPwaogvdQ.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/7OMAfDJikBxItZ2OcxAhAh77xpp.jpg',
    release_date: '2016-08-26',
    vote_average: 8.5,
    genres: ['Anime', 'Animation', 'Romance', 'Drama', 'Fantasy'],
    language: 'Japanese',
    runtime: 106,
    match_score: 98,
    agent_rationale: 'Makoto Shinkai emotionally shattering anime spectacle.'
  },
  {
    id: 'm-princessmononoke',
    title: 'Princess Mononoke (もののけ姫)',
    overview: 'On a journey to find the cure for a Tatarigami\'s curse, Ashitaka finds himself in the middle of a war between the forest gods and Tatara, a mining colony.',
    poster_path: 'https://image.tmdb.org/t/p/w780/cmyDbFkzV1qfWqfS4uCgq1B2n1A.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/m63b6iYJ3c6kQxR7yZ2O2hZ5N5d.jpg',
    release_date: '1997-07-12',
    vote_average: 8.4,
    genres: ['Anime', 'Animation', 'Fantasy', 'Adventure'],
    language: 'Japanese',
    runtime: 134,
    match_score: 97,
    agent_rationale: 'Hayao Miyazaki towering environmental fantasy epic.'
  },
  {
    id: 'm-laland',
    title: 'La La Land',
    overview: 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.',
    poster_path: 'https://image.tmdb.org/t/p/w780/uDO8zWDhfWwoFdKS4fzkVJt0Rf0.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/nlPCvjGzG5B58Z9pE0h9Xl7x6bS.jpg',
    release_date: '2016-12-09',
    vote_average: 8.0,
    genres: ['Romance', 'Comedy', 'Drama', 'Music'],
    language: 'English',
    runtime: 128,
    match_score: 97,
    agent_rationale: 'Damien Chazelle 6 Academy Award-winning modern Hollywood musical love letter.'
  },
  {
    id: 'm-titanic',
    title: 'Titanic',
    overview: '101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later. A young Rose boards the ship with her mother and fiance, and meets Jack Dawson.',
    poster_path: 'https://image.tmdb.org/t/p/w780/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/yDHYTfA3R0jFYba16jBB1jv8uaC.jpg',
    release_date: '1997-12-19',
    vote_average: 7.9,
    genres: ['Romance', 'Drama'],
    language: 'English',
    runtime: 194,
    match_score: 96,
    agent_rationale: 'James Cameron 11 Oscars record-tying romantic disaster epic.'
  },
  {
    id: 'm-pastlives',
    title: 'Past Lives',
    overview: 'Nora and Hae Sung, two deeply connected childhood friends, are wrested apart after Nora\'s family emigrates from South Korea. Decades later, they are reunited for one fateful week.',
    poster_path: 'https://image.tmdb.org/t/p/w780/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/2wkVhQ8cZ3Y7vX8pE6Z0o7d7V9a.jpg',
    release_date: '2023-06-02',
    vote_average: 8.0,
    genres: ['Romance', 'Drama'],
    language: 'Korean',
    runtime: 106,
    match_score: 95,
    agent_rationale: 'Exquisite, delicate exploration of love, destiny, and the Korean concept of In-Yun.'
  },
  {
    id: 'm-3idiots',
    title: '3 Idiots',
    overview: 'Two friends search for their long lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently, even as the rest of the world called them "idiots".',
    poster_path: 'https://image.tmdb.org/t/p/w780/66A9MqXOyVFCssoloscw79z8swQ.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/u78uN3F76YF4l6k5Wp9yP2P8u5c.jpg',
    release_date: '2009-12-25',
    vote_average: 8.4,
    genres: ['Comedy', 'Drama', 'Romance'],
    language: 'Hindi',
    runtime: 170,
    match_score: 98,
    agent_rationale: 'Beloved Rajkumar Hirani masterpiece celebrating passion, education, and friendship.'
  },
  {
    id: 'm-knivesout',
    title: 'Knives Out',
    overview: 'When renowned crime novelist Harlan Thrombey is found dead at his estate, inquisitive Detective Benoit Blanc is mysteriously enlisted to investigate.',
    poster_path: 'https://image.tmdb.org/t/p/w780/pThyQovXQrw2m0s9x82twj48Jq4.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/4HWAQu28e2yaWrtupFPGFkdNU7V.jpg',
    release_date: '2019-11-27',
    vote_average: 7.9,
    genres: ['Comedy', 'Mystery', 'Crime', 'Thriller'],
    language: 'English',
    runtime: 130,
    match_score: 95,
    agent_rationale: 'Rian Johnson deliciously entertaining whodunit with star-studded ensemble.'
  },
  {
    id: 'm-grandbudapest',
    title: 'The Grand Budapest Hotel',
    overview: 'The adventures of Gustave H, a legendary concierge at a famous European hotel between the wars, and Zero Moustafa, the lobby boy who becomes his most trusted friend.',
    poster_path: 'https://image.tmdb.org/t/p/w780/eWdyYQreja6JGCzqHWX9NZkt5BW.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/6cW3K6pQoE3gV3r3Qz6m8kF2P8w.jpg',
    release_date: '2014-03-07',
    vote_average: 8.1,
    genres: ['Comedy', 'Adventure'],
    language: 'English',
    runtime: 99,
    match_score: 96,
    agent_rationale: 'Wes Anderson visual poetry, symmetrical pastel framing, and madcap caper comedy.'
  }
];

export const MOCK_SONGS: Song[] = [
  // ── TRENDING / GLOBAL CHARTBUSTERS ──
  {
    id: 's-blinding-lights',
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    album: 'After Hours',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/6f/bc/e6/6fbce6c4-c38c-72d8-4fd0-66cfff32f679/20UMGIM12176.rgb.jpg/600x600bb.jpg',
    duration_sec: 200,
    genre: 'Trending',
    language: 'English',
    plays: '4,120,450,119',
    match_score: 99,
    agent_rationale: 'All-time streaming juggernaut with 80s synthwave vitality.'
  },
  {
    id: 's-starboy',
    title: 'Starboy',
    artist: 'The Weeknd, Daft Punk',
    album: 'Starboy',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/b5/92/bb/b592bb72-52e3-e756-9b26-9f56d08f47ab/16UMGIM67864.rgb.jpg/600x600bb.jpg',
    duration_sec: 230,
    genre: 'Trending',
    language: 'English',
    plays: '2,941,180,920',
    match_score: 98,
    agent_rationale: 'Matches your energetic evening sessions and neo-noir aesthetic.'
  },
  {
    id: 's-espresso',
    title: 'Espresso',
    artist: 'Sabrina Carpenter',
    album: 'Short n\' Sweet',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/57/e8/7b/57e87ba0-5057-9bb9-c247-ce7dbe426e89/24UMGIM55213.rgb.jpg/600x600bb.jpg',
    duration_sec: 175,
    genre: 'Trending',
    language: 'English',
    plays: '1,320,890,440',
    match_score: 97,
    agent_rationale: 'Breezy funk-pop viral anthem dominating global summer charts.'
  },
  {
    id: 's-as-it-was',
    title: 'As It Was',
    artist: 'Harry Styles',
    album: 'Harry\'s House',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/2a/19/fb/2a19fb85-2f70-9e44-f2a9-82abe679b88e/886449990061.jpg/600x600bb.jpg',
    duration_sec: 167,
    genre: 'Trending',
    language: 'English',
    plays: '3,210,040,180',
    match_score: 98,
    agent_rationale: 'Melancholic indie-synth masterpiece with unstoppable momentum.'
  },
  {
    id: 's-greedy',
    title: 'Greedy',
    artist: 'Tate McRae',
    album: 'THINK LATER',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/21/4a/c2/214ac20c-a66c-84a1-e357-f7e60b1932ca/196871542661.jpg/600x600bb.jpg',
    duration_sec: 131,
    genre: 'Trending',
    language: 'English',
    plays: '1,120,405,620',
    match_score: 96,
    agent_rationale: 'High-energy pop confidence anthem with addictive bass groove.'
  },

  // ── ROMANTIC SONGS & SOULFUL BALLADS ──
  {
    id: 's-darmiyaan',
    title: 'Darmiyaan',
    artist: 'Shafqat Amanat Ali & Clinton Cerejo',
    album: 'Jodi Breakers',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music18/v4/dc/53/46/dc534631-17ba-6932-250f-84dd558fc78e/8902894698481_cover.jpg/600x600bb.jpg',
    duration_sec: 349,
    genre: 'Romantic',
    language: 'Hindi',
    plays: '142,809,310',
    match_score: 99,
    agent_rationale: 'Soulful Bollywood romantic classic with soaring emotional vocals.'
  },
  {
    id: 's-kesariya',
    title: 'Kesariya',
    artist: 'Arijit Singh, Pritam',
    album: 'Brahmāstra',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/9f/13/ca/9f13ca3b-e533-03e0-f19a-f0aaa774581d/196589311191.jpg/600x600bb.jpg',
    duration_sec: 268,
    genre: 'Romantic',
    language: 'Hindi',
    plays: '890,340,120',
    match_score: 98,
    agent_rationale: 'Mesmerizing romantic ballad with lush orchestration and acoustic resonance.'
  },
  {
    id: 's-until-i-found-you',
    title: 'Until I Found You',
    artist: 'Stephen Sanchez',
    album: 'Easy On My Eyes',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/64/d2/c5/64d2c511-67f4-ae09-5153-d39c3da413a3/21UMGIM75467.rgb.jpg/600x600bb.jpg',
    duration_sec: 177,
    genre: 'Romantic',
    language: 'English',
    plays: '1,890,340,900',
    match_score: 97,
    agent_rationale: 'Vintage 1950s doo-wop romantic tribute with warm analog warmth.'
  },
  {
    id: 's-golden-hour',
    title: 'Golden Hour',
    artist: 'JVKE',
    album: 'this is what ____ feels like',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/8d/1a/7b/8d1a7b44-316f-7c7f-4380-935673fb697a/5056167175650.jpg/600x600bb.jpg',
    duration_sec: 209,
    genre: 'Romantic',
    language: 'English',
    plays: '1,450,220,105',
    match_score: 96,
    agent_rationale: 'Cinematic piano arpeggios that capture pure golden-lit romance.'
  },
  {
    id: 's-tum-hi-ho',
    title: 'Tum Hi Ho',
    artist: 'Arijit Singh, Mithoon',
    album: 'Aashiqui 2',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/bb/23/ee/bb23eeed-0c35-4f1d-2b11-485622777ae4/8902894353007_cover.jpg/600x600bb.jpg',
    duration_sec: 262,
    genre: 'Romantic',
    language: 'Hindi',
    plays: '1,200,890,300',
    match_score: 99,
    agent_rationale: 'Definitive romantic anthem of a generation with passionate crescendo.'
  },
  {
    id: 's-channa-mereya',
    title: 'Channa Mereya',
    artist: 'Arijit Singh, Pritam',
    album: 'Ae Dil Hai Mushkil',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/bc/6e/4d/bc6e4d0c-adec-b431-7b60-16f5689f9664/886446201597.jpg/600x600bb.jpg',
    duration_sec: 289,
    genre: 'Romantic',
    language: 'Hindi',
    plays: '950,210,400',
    match_score: 98,
    agent_rationale: 'Sufi-infused acoustic romance with heartbreaking emotional vocal delivery.'
  },
  {
    id: 's-raabta',
    title: 'Raabta',
    artist: 'Arijit Singh, Pritam',
    album: 'Agent Vinod',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music114/v4/dc/a5/46/dca54628-5ca4-148c-d5c3-6219abc886e1/8902894698825_cover.jpg/600x600bb.jpg',
    duration_sec: 243,
    genre: 'Romantic',
    language: 'Hindi',
    plays: '740,300,100',
    match_score: 97,
    agent_rationale: 'Intimate acoustic rhythm exploring unexplainable destined connections.'
  },
  {
    id: 's-gerua',
    title: 'Gerua',
    artist: 'Arijit Singh, Antara Mitra, Pritam',
    album: 'Dilwale',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/dd/c8/ee/ddc8ee1d-baeb-0c8b-383f-1eb21bd172c2/886445593280.jpg/600x600bb.jpg',
    duration_sec: 345,
    genre: 'Romantic',
    language: 'Hindi',
    plays: '830,120,500',
    match_score: 97,
    agent_rationale: 'Sweeping orchestral romance set against majestic cinematic landscapes.'
  },
  {
    id: 's-hawayein',
    title: 'Hawayein',
    artist: 'Arijit Singh, Pritam',
    album: 'Jab Harry Met Sejal',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/41/aa/e3/41aae321-0a81-2762-e0eb-c60844109fe7/886446683584.jpg/600x600bb.jpg',
    duration_sec: 290,
    genre: 'Romantic',
    language: 'Hindi',
    plays: '790,450,200',
    match_score: 96,
    agent_rationale: 'Gentle breeze acoustic guitars and tender poetic lyrics.'
  },
  {
    id: 's-perfect',
    title: 'Perfect',
    artist: 'Ed Sheeran',
    album: '÷ (Divide)',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/15/e6/e8/15e6e8a4-4190-6a8b-86c3-ab4a51b88288/190295851286.jpg/600x600bb.jpg',
    duration_sec: 263,
    genre: 'Romantic',
    language: 'English',
    plays: '2,890,300,500',
    match_score: 99,
    agent_rationale: 'Acoustic waltz celebration of timeless romance.'
  },
  {
    id: 's-thinking-out-loud',
    title: 'Thinking Out Loud',
    artist: 'Ed Sheeran',
    album: 'x (Multiply)',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/2d/36/f9/2d36f9a7-2c3e-ce0f-7fb6-036feecb221f/825646974450.jpg/600x600bb.jpg',
    duration_sec: 281,
    genre: 'Romantic',
    language: 'English',
    plays: '2,450,910,200',
    match_score: 98,
    agent_rationale: 'Blue-eyed soul ballad celebrating lifelong devotion and tender melody.'
  },
  {
    id: 's-photograph',
    title: 'Photograph',
    artist: 'Ed Sheeran',
    album: 'x (Multiply)',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/2d/36/f9/2d36f9a7-2c3e-ce0f-7fb6-036feecb221f/825646974450.jpg/600x600bb.jpg',
    duration_sec: 258,
    genre: 'Romantic',
    language: 'English',
    plays: '2,320,400,100',
    match_score: 97,
    agent_rationale: 'Nostalgic acoustic ballad about cherishing love across distance and time.'
  },
  {
    id: 's-die-with-a-smile',
    title: 'Die With A Smile',
    artist: 'Lady Gaga, Bruno Mars',
    album: 'Die With A Smile',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/11/ae/f2/11aef294-f57c-bab9-c9fc-529162984e62/24UMGIM85348.rgb.jpg/600x600bb.jpg',
    duration_sec: 251,
    genre: 'Romantic',
    language: 'English',
    plays: '1,450,800,900',
    match_score: 98,
    agent_rationale: 'Powerhouse vocal duet with vintage 70s soul and heartfelt devotion.'
  },
  {
    id: 's-just-the-way-you-are',
    title: 'Just the Way You Are',
    artist: 'Bruno Mars',
    album: 'Doo-Wops & Hooligans',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music114/v4/52/b1/45/52b1452b-229e-78db-231b-7b43fa0077cc/075679956491.jpg/600x600bb.jpg',
    duration_sec: 220,
    genre: 'Romantic',
    language: 'English',
    plays: '2,200,900,400',
    match_score: 96,
    agent_rationale: 'Pure upbeat romantic devotion celebrating unconditional admiration.'
  },
  {
    id: 's-all-of-me',
    title: 'All of Me',
    artist: 'John Legend',
    album: 'Love in the Future',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/22/71/b9/2271b906-85b3-06ee-e611-489b91df0b73/886444160742.jpg/600x600bb.jpg',
    duration_sec: 269,
    genre: 'Romantic',
    language: 'English',
    plays: '2,510,800,200',
    match_score: 99,
    agent_rationale: 'Iconic piano ballad expressing absolute, unconditional love.'
  },
  {
    id: 's-tere-bina',
    title: 'Tere Bina',
    artist: 'A.R. Rahman, Chinmayi',
    album: 'Guru',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/8d/8c/69/8d8c697e-f108-9e69-0cb1-475b45ab26a8/886970389020.jpg/600x600bb.jpg',
    duration_sec: 309,
    genre: 'Romantic',
    language: 'Hindi',
    plays: '620,900,100',
    match_score: 98,
    agent_rationale: 'A.R. Rahman romantic masterpiece with sublime Qawwali and violin motifs.'
  },
  {
    id: 's-the-scientist',
    title: 'The Scientist',
    artist: 'Coldplay',
    album: 'A Rush of Blood to the Head',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/b9/b4/2a/b9b42ad1-1e25-5096-da43-497a247e69a3/190295978051.jpg/600x600bb.jpg',
    duration_sec: 309,
    genre: 'Romantic',
    language: 'English',
    plays: '2,150,000,000',
    match_score: 97,
    agent_rationale: 'Haunting piano ballad about love, apology, and yearning to start again.'
  },

  // ── ROCK & HIGH-VOLTAGE ANTHEMS ──
  {
    id: 's-beautiful-things',
    title: 'Beautiful Things',
    artist: 'Benson Boone',
    album: 'Fireworks & Rollerblades',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/54/f4/92/54f49210-e260-b519-ebbd-f4f40ee710cd/054391342751.jpg/600x600bb.jpg',
    duration_sec: 180,
    genre: 'Rock',
    language: 'English',
    plays: '1,420,900,105',
    match_score: 98,
    agent_rationale: 'Global viral rock-pop ballad with explosive vocal crescendos.'
  },
  {
    id: 's-in-the-end',
    title: 'In The End',
    artist: 'Linkin Park',
    album: 'Hybrid Theory',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/53/a7/7f/53a77fab-c54c-a57b-8130-248fc12d0c80/093624948995.jpg/600x600bb.jpg',
    duration_sec: 216,
    genre: 'Rock',
    language: 'English',
    plays: '2,100,500,400',
    match_score: 99,
    agent_rationale: 'Immortal alternative rock monument with iconic dual-vocal delivery.'
  },
  {
    id: 's-bohemian-rhapsody',
    title: 'Bohemian Rhapsody',
    artist: 'Queen',
    album: 'A Night at the Opera',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/4d/08/2a/4d082a9e-7898-1aa1-a02f-339810058d9e/14DMGIM05632.rgb.jpg/600x600bb.jpg',
    duration_sec: 354,
    genre: 'Rock',
    language: 'English',
    plays: '2,650,420,800',
    match_score: 99,
    agent_rationale: 'The most legendary progressive rock suite in musical history.'
  },
  {
    id: 's-believer',
    title: 'Believer',
    artist: 'Imagine Dragons',
    album: 'Evolve',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/11/7a/b8/117ab805-6811-8929-18b9-0fad7baf0c25/17UMGIM98210.rgb.jpg/600x600bb.jpg',
    duration_sec: 204,
    genre: 'Rock',
    language: 'English',
    plays: '3,050,400,200',
    match_score: 96,
    agent_rationale: 'Pounding percussion, roaring guitars, and defiant arena energy.'
  },
  {
    id: 's-sweet-child',
    title: 'Sweet Child O\' Mine',
    artist: 'Guns N\' Roses',
    album: 'Appetite for Destruction',
    album_art: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80',
    duration_sec: 356,
    genre: 'Rock',
    language: 'English',
    plays: '2,150,000,100',
    match_score: 97,
    agent_rationale: 'Timeless hard rock anthem with one of the greatest guitar riffs of all time.'
  },
  {
    id: 's-yellow',
    title: 'Yellow',
    artist: 'Coldplay',
    album: 'Parachutes',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/f5/93/8c/f5938c49-964c-31d1-4b33-78b634f71fb7/190295978075.jpg/600x600bb.jpg',
    duration_sec: 269,
    genre: 'Rock',
    language: 'English',
    plays: '2,400,900,100',
    match_score: 98,
    agent_rationale: 'Sublime chiming acoustic guitars and tender anthemic devotion.'
  },
  {
    id: 's-fix-you',
    title: 'Fix You',
    artist: 'Coldplay',
    album: 'X&Y',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/0c/82/48/0c8248a8-4a5b-d30d-8056-f32d650d2fc9/190295978068.jpg/600x600bb.jpg',
    duration_sec: 295,
    genre: 'Rock',
    language: 'English',
    plays: '1,950,200,400',
    match_score: 97,
    agent_rationale: 'Gentle organ swell culminating in an explosive emotional guitar crescendo.'
  },
  {
    id: 's-viva-la-vida',
    title: 'Viva La Vida',
    artist: 'Coldplay',
    album: 'Viva La Vida',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/52/aa/85/52aa851f-15b7-6322-f91f-df84b15b7b19/190295978044.jpg/600x600bb.jpg',
    duration_sec: 242,
    genre: 'Rock',
    language: 'English',
    plays: '2,200,900,500',
    match_score: 98,
    agent_rationale: 'Sweeping orchestral strings and triumphant art-rock percussion.'
  },
  {
    id: 's-numb',
    title: 'Numb',
    artist: 'Linkin Park',
    album: 'Meteora',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/13/44/05/134405bd-9e27-a678-8953-b5f724201f95/093624948988.jpg/600x600bb.jpg',
    duration_sec: 187,
    genre: 'Rock',
    language: 'English',
    plays: '2,450,120,800',
    match_score: 99,
    agent_rationale: 'Iconic synth intro, blistering guitars, and Chester Bennington immortal vocals.'
  },
  {
    id: 's-dont-stop-me-now',
    title: 'Don\'t Stop Me Now',
    artist: 'Queen',
    album: 'Jazz',
    album_art: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
    duration_sec: 209,
    genre: 'Rock',
    language: 'English',
    plays: '2,100,500,200',
    match_score: 97,
    agent_rationale: 'Pure exhilarating piano-driven joy led by Freddie Mercury electrifying charm.'
  },
  {
    id: 's-demons',
    title: 'Demons',
    artist: 'Imagine Dragons',
    album: 'Night Visions',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/1f/fa/09/1ffa092f-f52f-4a66-7d10-4cc5982dc747/12UMGIM46901.rgb.jpg/600x600bb.jpg',
    duration_sec: 177,
    genre: 'Rock',
    language: 'English',
    plays: '2,300,910,200',
    match_score: 96,
    agent_rationale: 'Heartfelt vulnerability meets driving indie-rock drums and massive chorus.'
  },

  // ── POP HITS & GLOBAL GROOVES ──
  {
    id: 's-senorita',
    title: 'Señorita',
    artist: 'Shawn Mendes, Camila Cabello',
    album: 'Shawn Mendes (Deluxe)',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/46/fe/4a/46fe4a39-feb4-7b8b-97b9-0187d49a46bd/19UMGIM53914.rgb.jpg/600x600bb.jpg',
    duration_sec: 191,
    genre: 'Pop',
    language: 'Spanish',
    plays: '2,890,140,229',
    match_score: 98,
    agent_rationale: 'Seductive Latin pop duet with irresistible acoustic rhythm.'
  },
  {
    id: 's-lover',
    title: 'Lover',
    artist: 'Diljit Dosanjh',
    album: 'MoonChild Era',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/8a/89/e4/8a89e445-d2c6-f8ac-a828-27818b0c1afe/859749638209_cover.jpg/600x600bb.jpg',
    duration_sec: 198,
    genre: 'Pop',
    language: 'Punjabi',
    plays: '310,420,119',
    match_score: 96,
    agent_rationale: 'Upbeat Punjabi dance-pop with infectious melodic hooks.'
  },
  {
    id: 's-levitating',
    title: 'Levitating',
    artist: 'Dua Lipa',
    album: 'Future Nostalgia',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/6c/11/d6/6c11d681-aa3a-d59e-4c2e-f77e181026ab/190295092665.jpg/600x600bb.jpg',
    duration_sec: 203,
    genre: 'Pop',
    language: 'English',
    plays: '2,420,000,300',
    match_score: 97,
    agent_rationale: 'Futuristic nu-disco pop with a dazzling cosmic dance beat.'
  },
  {
    id: 's-cruel-summer',
    title: 'Cruel Summer',
    artist: 'Taylor Swift',
    album: 'Lover',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/49/3d/ab/493dab54-f920-9043-6181-80993b8116c9/19UMGIM53909.rgb.jpg/600x600bb.jpg',
    duration_sec: 178,
    genre: 'Pop',
    language: 'English',
    plays: '2,600,890,100',
    match_score: 98,
    agent_rationale: 'Euphoric synthpop bridge and explosive emotional release.'
  },
  {
    id: 's-bad-guy',
    title: 'bad guy',
    artist: 'Billie Eilish',
    album: 'WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/1a/37/d1/1a37d1b1-8508-54f2-f541-bf4e437dda76/19UMGIM05028.rgb.jpg/600x600bb.jpg',
    duration_sec: 194,
    genre: 'Pop',
    language: 'English',
    plays: '2,580,200,900',
    match_score: 95,
    agent_rationale: 'Minimalist bassline and whisper-pop production that reshaped modern pop.'
  },

  // ── HIP-HOP & URBAN BEATS ──
  {
    id: 's-humble',
    title: 'HUMBLE.',
    artist: 'Kendrick Lamar',
    album: 'DAMN.',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/ab/16/ef/ab16efe9-e7f1-66ec-021c-5592a23f0f9e/17UMGIM88793.rgb.jpg/600x600bb.jpg',
    duration_sec: 177,
    genre: 'Hip-Hop',
    language: 'English',
    plays: '2,150,890,200',
    match_score: 98,
    agent_rationale: 'High energy beat with driving 808s and razor-sharp bars.'
  },
  {
    id: 's-sicko-mode',
    title: 'SICKO MODE',
    artist: 'Travis Scott, Drake',
    album: 'ASTROWORLD',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/e7/49/8f/e7498f65-df8f-bead-d6e3-2a8d4d642a79/886447235317.jpg/600x600bb.jpg',
    duration_sec: 312,
    genre: 'Hip-Hop',
    language: 'English',
    plays: '2,340,900,400',
    match_score: 97,
    agent_rationale: 'Three distinct beat switches forging a monumental trap symphony.'
  },
  {
    id: 's-gods-plan',
    title: 'God\'s Plan',
    artist: 'Drake',
    album: 'Scorpion',
    album_art: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    duration_sec: 198,
    genre: 'Hip-Hop',
    language: 'English',
    plays: '2,500,400,100',
    match_score: 95,
    agent_rationale: 'Breezy melodic hip-hop anthem celebrating triumph and loyalty.'
  },
  {
    id: 's-goosebumps',
    title: 'goosebumps',
    artist: 'Travis Scott, Kendrick Lamar',
    album: 'Birds in the Trap Sing McKnight',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music114/v4/b8/e5/27/b8e527c8-aaf4-c7b7-5562-c479458ed7d9/886446092645.jpg/600x600bb.jpg',
    duration_sec: 243,
    genre: 'Hip-Hop',
    language: 'English',
    plays: '2,100,200,900',
    match_score: 96,
    agent_rationale: 'Dark hypnotic melodies with intoxicating nighttime bounce.'
  },

  // ── CINEMATIC SOUNDTRACKS & MASTERPIECES ──
  {
    id: 's-cornfield',
    title: 'Cornfield Chase',
    artist: 'Hans Zimmer',
    album: 'Interstellar (Original Motion Picture Soundtrack)',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/f4/5b/73/f45b735a-8d7a-9713-b217-0f8e1593c28b/794043201943.jpg/600x600bb.jpg',
    duration_sec: 127,
    genre: 'Soundtrack',
    language: 'English',
    plays: '284,291,402',
    match_score: 99,
    agent_rationale: 'Monumental pipe organ crescendo defining cosmic cinema.'
  },
  {
    id: 's-time',
    title: 'Time',
    artist: 'Hans Zimmer',
    album: 'Inception (Music from the Motion Picture)',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/2b/62/eb/2b62ebd7-aa99-988a-0fee-714162f6fbeb/093624965008.jpg/600x600bb.jpg',
    duration_sec: 275,
    genre: 'Soundtrack',
    language: 'English',
    plays: '390,120,400',
    match_score: 99,
    agent_rationale: 'Sublime ascending string progression evoking deep transcendence.'
  },
  {
    id: 's-can-you-hear-the-music',
    title: 'Can You Hear The Music',
    artist: 'Ludwig Göransson',
    album: 'Oppenheimer (Original Motion Picture Soundtrack)',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/27/fa/ca/27faca2e-7f7a-cf17-ae3e-647294d52713/697.jpg/600x600bb.jpg',
    duration_sec: 110,
    genre: 'Soundtrack',
    language: 'English',
    plays: '210,400,900',
    match_score: 98,
    agent_rationale: 'Dizzying 21 tempo changes capturing theoretical physics in sonic form.'
  },
  {
    id: 's-chevaliers',
    title: 'Chevaliers de Sangreal',
    artist: 'Hans Zimmer',
    album: 'The Da Vinci Code Soundtrack',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/12/f8/4f/12f84f20-200e-230d-de5f-ad1c890efc4a/06UMGIM19765.rgb.jpg/600x600bb.jpg',
    duration_sec: 247,
    genre: 'Soundtrack',
    language: 'English',
    plays: '195,400,100',
    match_score: 97,
    agent_rationale: 'Intricate string ostinato with soaring chorale crescendo.'
  },
  {
    id: 's-mountains',
    title: 'Mountains',
    artist: 'Hans Zimmer',
    album: 'Interstellar (Original Motion Picture Soundtrack)',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/f4/5b/73/f45b735a-8d7a-9713-b217-0f8e1593c28b/794043201943.jpg/600x600bb.jpg',
    duration_sec: 219,
    genre: 'Soundtrack',
    language: 'English',
    plays: '260,100,500',
    match_score: 98,
    agent_rationale: 'Ticking clock urgency meeting towering wall-of-sound orchestration.'
  },
  {
    id: 's-kun-faya-kun',
    title: 'Kun Faya Kun',
    artist: 'A.R. Rahman, Mohit Chauhan, Javed Ali',
    album: 'Rockstar',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/56/ac/41/56ac41f7-99f3-3eae-3b07-443167292c4e/8902894697408_cover.jpg/600x600bb.jpg',
    duration_sec: 473,
    genre: 'Soundtrack',
    language: 'Hindi',
    plays: '810,450,200',
    match_score: 99,
    agent_rationale: 'Sublime Sufi spiritual transcendence composed by A.R. Rahman.'
  },
  {
    id: 's-jai-ho',
    title: 'Jai Ho',
    artist: 'A.R. Rahman, Sukhwinder Singh',
    album: 'Slumdog Millionaire',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/a8/92/ca/a892ca65-89ae-7ce3-ce08-e5aef83cfd11/00602527009230.rgb.jpg/600x600bb.jpg',
    duration_sec: 319,
    genre: 'Soundtrack',
    language: 'Hindi',
    plays: '740,200,800',
    match_score: 98,
    agent_rationale: 'Academy Award-winning global anthem celebrating victory and joy.'
  },

  // ── LO-FI & CHILL FOCUS BEATS ──
  {
    id: 's-resonance',
    title: 'Resonance',
    artist: 'HOME',
    album: 'Odyssey',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/98/75/dd/9875dd83-34f6-40ef-3987-fd13646409be/5034644208930_homeodyssey.jpg/600x600bb.jpg',
    duration_sec: 212,
    genre: 'Lo-Fi',
    language: 'English',
    plays: '492,109,240',
    match_score: 97,
    agent_rationale: 'Calibrated for deep coding focus with warm analog synthesizers.'
  },
  {
    id: 's-nightcall',
    title: 'Nightcall',
    artist: 'Kavinsky',
    album: 'OutRun',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/c1/2d/fe/c12dfe8f-cdf6-e179-d69a-8ec35f760266/00602537248681.rgb.jpg/600x600bb.jpg',
    duration_sec: 259,
    genre: 'Lo-Fi',
    language: 'English',
    plays: '380,240,190',
    match_score: 96,
    agent_rationale: 'Midnight retro-electro driving score with robotic vocal stylings.'
  },
  {
    id: 's-a-walk',
    title: 'A Walk',
    artist: 'Tycho',
    album: 'Dive',
    album_art: 'https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/46/be/ed/46beed8a-5d0f-1077-cbeb-aace15e69f44/cover.jpg/600x600bb.jpg',
    duration_sec: 316,
    genre: 'Lo-Fi',
    language: 'English',
    plays: '190,400,200',
    match_score: 95,
    agent_rationale: 'Lush ambient soundscapes with soothing organic guitar textures.'
  }
];
