import { Movie, Song } from '@/types';

export const MOCK_MOVIES: Movie[] = [
  {
    id: 'm-forrest-gump',
    title: 'Forrest Gump',
    overview: 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined possible. Yet, despite all he has achieved, his one true love eludes him.',
    poster_path: 'https://image.tmdb.org/t/p/w780/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/qdIMHd4sEfJSckfVJfKQvisL02a.jpg',
    release_date: '1994-07-06',
    vote_average: 8.5,
    genres: ['Drama', 'Romance', 'Comedy'],
    language: 'English',
    runtime: 142,
    match_score: 99,
    agent_rationale: 'Academy Award Winner for Best Picture. Pure cinematic storytelling with Tom Hanks unforgettable performance.'
  },
  {
    id: 'm-mirzapur',
    title: 'Mirzapur',
    overview: 'A shocking incident at a wedding procession ignites a series of events entangling two families in the lawless city of Mirzapur.',
    poster_path: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=700&auto=format&fit=crop&q=80',
    backdrop_path: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=1200&auto=format&fit=crop&q=80',
    release_date: '2024-07-05',
    vote_average: 8.5,
    genres: ['Action', 'Thriller', 'Drama'],
    language: 'Hindi',
    runtime: 55,
    match_score: 97,
    agent_rationale: 'High-stakes gritty Indian crime drama with raw character arcs.'
  },
  {
    id: 'm-shawshank',
    title: 'The Shawshank Redemption',
    overview: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    poster_path: 'https://image.tmdb.org/t/p/w780/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
    release_date: '1994-09-23',
    vote_average: 9.3,
    genres: ['Drama', 'Classic'],
    language: 'English',
    runtime: 142,
    match_score: 98,
    agent_rationale: 'All-time IMDb #1 masterpiece of resilience, hope, and friendship.'
  },
  {
    id: 'm-american-psycho',
    title: 'American Psycho',
    overview: 'A wealthy New York City investment banking executive hides his alternate psychopathic ego from his co-workers and friends.',
    poster_path: 'https://image.tmdb.org/t/p/w780/9uGHEgsiUXjCNq8wdq4r49YL8A1.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/qdIMHd4sEfJSckfVJfKQvisL02a.jpg',
    release_date: '2000-04-14',
    vote_average: 7.6,
    genres: ['Thriller', 'Comedy', 'Drama'],
    language: 'English',
    runtime: 102,
    match_score: 94,
    agent_rationale: 'Sharp dark satire and psychological horror with iconic performances.'
  },
  {
    id: 'm-dark-knight',
    title: 'The Dark Knight',
    overview: 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets.',
    poster_path: 'https://image.tmdb.org/t/p/w780/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
    release_date: '2008-07-18',
    vote_average: 8.5,
    genres: ['Action', 'Crime', 'Drama', 'Thriller'],
    language: 'English',
    runtime: 152,
    match_score: 99,
    agent_rationale: 'Christopher Nolan masterpiece featuring Heath Ledger legendary Oscar-winning performance.'
  },
  {
    id: 'm-parasite',
    title: 'Parasite (기생충)',
    overview: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    poster_path: 'https://image.tmdb.org/t/p/w780/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg',
    release_date: '2019-10-11',
    vote_average: 8.5,
    genres: ['Thriller', 'Drama', 'Comedy'],
    language: 'Korean',
    runtime: 132,
    match_score: 97,
    agent_rationale: 'Bong Joon-ho Oscar-winning masterpiece blending razor-sharp satire and suspense.'
  },
  {
    id: 'm-spiritedaway',
    title: 'Spirited Away (千と千尋の神隠し)',
    overview: 'During her family’s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
    poster_path: 'https://image.tmdb.org/t/p/w780/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/mSDsSDwaP3E7dviUU2ioXPsq9d2.jpg',
    release_date: '2001-07-20',
    vote_average: 8.6,
    genres: ['Anime', 'Sci-Fi', 'Adventure'],
    language: 'Japanese',
    runtime: 125,
    match_score: 98,
    agent_rationale: 'Hayao Miyazaki and Studio Ghibli crowning achievement in fantasy animation.'
  },
  {
    id: 'm-inception',
    title: 'Inception',
    overview: 'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: inception.',
    poster_path: 'https://image.tmdb.org/t/p/w780/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
    release_date: '2010-07-16',
    vote_average: 8.4,
    genres: ['Action', 'Sci-Fi', 'Adventure'],
    language: 'English',
    runtime: 148,
    match_score: 98,
    agent_rationale: 'Mind-bending dream heist cinema with Hans Zimmer iconic score.'
  },
  {
    id: 'm-interstellar',
    title: 'Interstellar',
    overview: 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
    poster_path: 'https://image.tmdb.org/t/p/w780/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/pbrkL804c8yAv3zBZR4QPEafpAR.jpg',
    release_date: '2014-11-07',
    vote_average: 8.7,
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    language: 'English',
    runtime: 169,
    match_score: 99,
    agent_rationale: 'Epic space voyage exploring love, time dilation, and human survival.'
  },
  {
    id: 'm-gladiator',
    title: 'Gladiator',
    overview: 'In the year 180, the death of Emperor Marcus Aurelius throws the Roman Empire into turmoil. When Maximus Decimus Meridius is betrayed and his family murdered, he is forced into slavery as a gladiator to avenge their deaths.',
    poster_path: 'https://image.tmdb.org/t/p/w780/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/3ZVEtQxVPpEp5LNpAULDcxadTU3.jpg',
    release_date: '2000-05-05',
    vote_average: 8.5,
    genres: ['Action', 'Drama', 'Adventure'],
    language: 'English',
    runtime: 155,
    match_score: 97,
    agent_rationale: 'Epic historical drama directed by Ridley Scott with timeless score by Hans Zimmer.'
  },
  {
    id: 'm-batman',
    title: 'The Batman',
    overview: 'In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.',
    poster_path: 'https://image.tmdb.org/t/p/w780/74xTEgt7R36Fpooo50r9T25onhq.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/tRS6jvPM9qPrrnx2KRx2ew96Yot.jpg',
    release_date: '2022-03-04',
    vote_average: 8.2,
    genres: ['Action', 'Thriller', 'Drama'],
    language: 'English',
    runtime: 176,
    match_score: 93,
    agent_rationale: 'Dark atmospheric crime thriller with intense pacing and Michael Giacchino score.'
  }
];

export const MOCK_SONGS: Song[] = [
  {
    id: 's-darmiyaan',
    title: 'Darmiyaan',
    artist: 'Shafqat Amanat Ali & Clinton Cerejo',
    album: 'Jodi Breakers',
    album_art: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80',
    duration_sec: 349,
    genre: 'Romantic',
    language: 'Hindi',
    plays: '142,809,310',
    match_score: 99,
    agent_rationale: 'Soulful Bollywood romantic classic with soaring vocals.'
  },
  {
    id: 's-senorita',
    title: 'Señorita',
    artist: 'Shawn Mendes, Camila Cabello',
    album: 'Shawn Mendes (Deluxe)',
    album_art: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80',
    duration_sec: 191,
    genre: 'Pop',
    language: 'Spanish',
    plays: '2,890,140,229',
    match_score: 98,
    agent_rationale: 'Seductive Latin pop duet with irresistible acoustic rhythm.'
  },
  {
    id: 's-gajanana',
    title: 'Gajanana',
    artist: 'Sukhwinder Singh',
    album: 'Bajirao Mastani',
    album_art: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
    duration_sec: 214,
    genre: 'Classical',
    language: 'Hindi',
    plays: '89,450,112',
    match_score: 97,
    agent_rationale: 'Powerful, thunderous traditional devotional anthem.'
  },
  {
    id: 's-beautiful-things',
    title: 'Beautiful Things',
    artist: 'Benson Boone',
    album: 'Fireworks & Rollerblades',
    album_art: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&auto=format&fit=crop&q=80',
    duration_sec: 180,
    genre: 'Rock',
    language: 'English',
    plays: '1,420,900,105',
    match_score: 96,
    agent_rationale: 'Global viral rock-pop ballad with explosive vocal crescendos.'
  },
  {
    id: 's-starboy',
    title: 'Starboy',
    artist: 'The Weeknd, Daft Punk',
    album: 'Starboy',
    album_art: 'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&auto=format&fit=crop&q=80',
    duration_sec: 230,
    genre: 'Electronic',
    language: 'English',
    plays: '2,941,180,920',
    match_score: 97,
    agent_rationale: 'Matches your energetic evening sessions and neo-noir aesthetic.'
  },
  {
    id: 's-humble',
    title: 'HUMBLE.',
    artist: 'Kendrick Lamar',
    album: 'DAMN.',
    album_art: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&auto=format&fit=crop&q=80',
    duration_sec: 177,
    genre: 'Hip-Hop',
    language: 'English',
    plays: '2,150,890,200',
    match_score: 95,
    agent_rationale: 'High energy beat with driving 808s for intense workout sessions.'
  },
  {
    id: 's-cornfield',
    title: 'Cornfield Chase',
    artist: 'Hans Zimmer',
    album: 'Interstellar (Original Motion Picture Soundtrack)',
    album_art: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80',
    duration_sec: 127,
    genre: 'Classical',
    language: 'English',
    plays: '184,291,402',
    match_score: 99,
    agent_rationale: 'Direct score alignment with your top-rated film Interstellar.'
  },
  {
    id: 's-resonance',
    title: 'Resonance',
    artist: 'HOME',
    album: 'Odyssey',
    album_art: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    duration_sec: 212,
    genre: 'Lo-Fi',
    language: 'English',
    plays: '492,109,240',
    match_score: 95,
    agent_rationale: 'Calibrated for deep coding focus with warm analog synthesizers.'
  },
  {
    id: 's-lover',
    title: 'Lover',
    artist: 'Diljit Dosanjh',
    album: 'MoonChild Era',
    album_art: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    duration_sec: 198,
    genre: 'Pop',
    language: 'Punjabi',
    plays: '310,420,119',
    match_score: 94,
    agent_rationale: 'Upbeat Punjabi dance-pop with infectious melodic hooks.'
  }
];
